name: ff-library-build-workflow
run-name: Workflow triggered by @${{ github.actor }}
on: [push, pull_request]
jobs:
  build:
    name: build-ts
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
